traefik:
  image: traefik
  container_name: traefik
  command: "--web --docker --docker.domain=${domain} --acme --acme.email=${email} --acme.storagefile=/acme.json --acme.ondemand=true --acme.entrypoint=https"
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/dev/null:/traefik.toml"
    - "$PWD/acme.json:/acme.json"
  labels:
    - "traefik.frontend.rule=Host:${host}"
    - "traefik.port=8080"
    - "traefik.enable=true"
    - "traefik.frontend.entryPoints=${entrypoints}"